apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: project 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: project 
  template: 
    metadata: 
      labels: 
        app: project 
    spec: 
      containers: 
      - name: custom 
        image: docker6767/image 
        ports: 
        - containerPort: 80 
 
Create SVC.yml 
apiVersion: v1 
kind: Service 
metadata: 
name: my-custom-deployment 
spec: 
type: NodePort 
ports: - targetPort: 80
port: 80
nodePort: 30008
selector:
app: custom
